services:
  - type: web
    name: ampyr-doc-translator
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: AZURE_TRANSLATOR_KEY
        sync: false
      - key: AZURE_TRANSLATOR_REGION
        sync: false
      - key: AZURE_TRANSLATOR_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        sync: false
